### ISSUE TITLE
Where are the generated images of "pick_heat_then_place_in_recap" in your provided training images ? 

### ISSUE THREAD

**Issue by wqshmzh** [snumprlab/cl-alfred#10]
Thanks for providing the generated images in https://huggingface.co/datasets/byeonghwikim/abp_images/tree/main/train
However, there are only 6 zip files without the file named as "pick_heat_then_place_in_recap.zip". Would you mind uploading this ? Otherwise the dataset is broken.

**Comment by bhkim94** [comment]
Thanks for pointing this out. I've just uploaded the one.
