### ISSUE TITLE
Incompatibility between numpy-quaternion==2022.4.2 and training environment setup

### ISSUE THREAD

**Issue by VidushiRawat** [snumprlab/cl-alfred#13]
I am getting an error while installing the wheel for numpy-quaternion==2022.4.2 for the training environment setup.

The error message is something like this:
fatal error: too many errors emitted, stopping now [-ferror-limit=]
      20 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numpy-quaternion
Failed to build numpy-quaternion
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (numpy-quaternion)

**Comment by bhkim94** [comment]
Hi @VidushiRawat 

Thank you for having an interest in our work!

I installed this with exactly the same commands for the training env setup in README, but I didn't observe such errors.
Can you provide more details on your PC environment? Which instructions did you use?

**Comment by VidushiRawat** [comment]
Hi @bhkim94,

Thank you for reaching out. I had issues while installing dependencies using requirements_train.txt. There were some incompatibility issues between numpy version and numpy-quaternion. However, I tried again using another method and it seems to be working now. I am using MacOS and was running pip install -r requirements_train.txt
