### ISSUE TITLE
Query: data/json_feat_2.1.0 

### ISSUE THREAD

**Issue by VidushiRawat** [snumprlab/cl-alfred#15]
Hi,
Before cloning the huggingface repo, there is already data present in data/json_feat_2.1.0 due to which the cloning is not working. Are we supposed to remove these files and clone the hugging face repo or do these files have some significance.

Also, I am getting the following error while training:
Traceback (most recent call last):
  File "models/train/train_seq2seq.py", line 171, in <module>
    model.run_train(args=args)
  File "/data/2rawat/cl-alfred/cl-alfred/models/model/seq2seq.py", line 81, in run_train
    cl_method.online_step(data, samples_cnt)
  File "/data/2rawat/cl-alfred/cl-alfred/methods/cama.py", line 29, in online_step
    info, logits = self.online_train(
  File "/data/2rawat/cl-alfred/cl-alfred/methods/cama.py", line 125, in online_train
    feat = self.model.featurize(batch)
  File "/data/2rawat/cl-alfred/cl-alfred/models/model/seq2seq_im_mask.py", line 138, in featurize
    im = torch.load(os.path.join(root, self.feat_pt))
  File "/export/home/2rawat/anaconda3/envs/cl-alfred-train/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/export/home/2rawat/anaconda3/envs/cl-alfred-train/lib/python3.8/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

I am concerned if it is due to the files not being present.

Please clarify.

**Comment by bhkim94** [comment]
Hi,

> Are we supposed to remove these files and clone the hugging face repo or do these files have some significance.

Can you try to clone the huggingface repo after removing the data/json_feat_2.1.0 in this repo?

> I am concerned if it is due to the files not being present.

It may be not because that's not some file not found errors.
The error comes from loading visual features, `im = torch.load(...)` and some visual features downloaded might be corrupted (or not fully downloaded). Can you try, like the first question, to clone the hugging face repo again?

**Comment by VidushiRawat** [comment]
I tried cloning the repo again. However, it has been running for long and the folder size has already increased 2.0 TB. In the description, it mentions that the data is approx 1.6 TB.
<img width="710" alt="image" src="https://github.com/user-attachments/assets/d5c93cdc-5a86-496c-ad50-8606b21b4a21">

Is it expected to be this much?
I have limited storage beyond this and the process is still running. How much more data should I expect?

**Comment by bhkim94** [comment]
Hmm, that's weird. It should not take that much.
Can you share a list of `.pt` or `.pth` files (should contain `feat_conv_panoramic`) in any episode, trial in `ls data/json_feat_2.1.0/train/<episode>/<trial>`?

**Comment by VidushiRawat** [comment]
<img width="918" alt="image" src="https://github.com/user-attachments/assets/46efc21f-2416-4cc6-ae16-9f54647884f8">

This is the list of .pt files from one of the episode trials

**Comment by bhkim94** [comment]
Hi, sorry for late reply.

Can you share the size of the `.pt` files listed above, each? I want to make sure that each visual feature file takes the same amount of space.
And, can you also check if there is any hidden files taking so much space there?

**Comment by VidushiRawat** [comment]
<img width="727" alt="image" src="https://github.com/user-attachments/assets/b866624e-6246-4913-b21c-13e870c6d396">

This is the size of the .pt files. Apart from the train folder there seem to be a lot of preprocessed file with ann_x.json files in them.

<img width="746" alt="image" src="https://github.com/user-attachments/assets/ccd5fb24-a4d5-4771-8535-295cd9ac730e">

**Comment by bhkim94** [comment]
Thank you for checking that. The file size looks good. Can you also try `du -hs .git`?

**Comment by VidushiRawat** [comment]
<img width="714" alt="image" src="https://github.com/user-attachments/assets/76dd7e92-33e6-4e1f-b300-3e1ff0ab8a07">

Seems to be consuming a lot of memory.

**Comment by bhkim94** [comment]
Just remove that after cloning the dataset. You don't need it.

**Comment by VidushiRawat** [comment]
Perfect, I will do so.
Thanks for your support.

**Comment by bhkim94** [comment]
Sure, no problem!
