### ISSUE TITLE
Query for the model evaluation

### ISSUE THREAD

**Issue by VidushiRawat** [snumprlab/cl-alfred#17]
Hi @bhkim94,
I had a query on the model evaluation. After training the model, we have 7 .pth files created (1 for each behavior) and 4 for the environment. Please confirm if my understanding is correct, for each model I need to evaluate different `incremental_type`. So, it would be 7 evaluations for 1 behaviour and total 49 evaluations for all in the case of `valid_seen` splits and another 49 for `valid_unseen` and similarly for the `environment_il `setup. Is this interpretation correct?

Also, is there a specific order that we have to follow for evaluation like starting with the task on which the model was trained and then evaluating the increasing complexity of `incremental_type` or it could be random?

Thanks in advance

**Comment by bhkim94** [comment]
Hi @VidushiRawat,

> it would be 7 evaluations for 1 behaviour and total 49 evaluations for all in the case of valid_seen splits and another 49 for valid_unseen and similarly for the environment_il setup. Is this interpretation correct?

No, you don't need 49 evaluations. For `behavior_il` for each `stream_seed`, we have 7 weights and you only need 7 evaluations in total. For $A_{last}$ metrics, you only need to check the performance of the last-behavior model. For $A_{avg}$, you need to take the average of the performances of the 7 models. You can get the metrics for `environment_il` similarly (i.e., $A_{last}$ with the last-environment model, $A_{avg}$ with the average of the 4 models' performances).

> Also, is there a specific order that we have to follow for evaluation like starting with the task on which the model was trained and then evaluating the increasing complexity of incremental_type or it could be random?

For each `stream_seed`, `behavior_il` and `environment_il` have their different orders, which can be found in our paper's appendix or [our code](https://github.com/snumprlab/cl-alfred/tree/master/embodied_split), and thus, the model should be evaluated in a specific order.

Hope this helps.

**Comment by VidushiRawat** [comment]
Thanks @bhkim94, this clarifies the query.
