### ISSUE TITLE
Missing tests_seen and unseen folders in dataset

### ISSUE THREAD

**Issue by JACK-Chen-2019** [snumprlab/cl-alfred#2]
I have met the same problem as seen in https://github.com/gistvision/moca/issues/7

**Comment by JACK-Chen-2019** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/json_feat_2.1.0/train/look_at_obj_in_light-Box-None-FloorLamp-212/trial_T20190908_193427_340509/traj_data.json'

However, in the downloaded directory, there is no traj_data.json file, but three ann.json files instead:
/json_feat_2.1.0/look_at_obj_in_light-Box-None-FloorLamp-212/trial_T20190908_193427_340509/pp/
ann_0.json
ann_1.json
ann_2.json

**Comment by bhkim94** [comment]
Hi @JACK-Chen-2019,

Thanks for having an interest in our work!

Can you share your command to reproduce the error?
This is quite unexpected because our code is expected to use `ann_x.json`, not `traj_data.json`.

Thanks

**Comment by JACK-Chen-2019** [comment]
Thanks for your replay. I don't have the 'pp.vocab' file and it needs to run with --preprocess. And it will run `dataset.preprocess_splits(splits)` in models/train/train_seq2seq.py line 152. And then it will run  `json_path = os.path.join(self.args.data, k, task['task'], 'traj_data.json')`.

**Comment by bhkim94** [comment]
I see. I've just added our `pp.vocab` in the Huggingface repo.
Can you download it and put it in the path `data/json_2.1.0`?
As we provide `pp.vocab`, the code should run without `preprocess`.
