### ISSUE TITLE
dataset download

### ISSUE THREAD

**Issue by hjson1022** [snumprlab/cl-alfred#5]
I got the error message when I tried to download the dataset from huggingface:
repository 'https://huggingface.co/byeonghwikim/abp_dataset/' not found

So, I tried the following comment:
git clone https://huggingface.co/datasets/byeonghwikim/abp_dataset json_feat_2.1.0

But, there is an error message in the part of loading resnet features (138 lines in seq2seq_im_mask.py file):
_pickle.UnpicklingError: invalid load key, 'v'
(I already tried to download dataset several times.)

Please reply to my question.
Thanks.

**Comment by bhkim94** [comment]
Hi @hjson1022,

Thank you for having an interest in our work!

> I got the error message when I tried to download the dataset from huggingface:
repository 'https://huggingface.co/byeonghwikim/abp_dataset/' not found

Thank you for pointing this out. I've just modified it.

> So, I tried the following comment:
git clone https://huggingface.co/datasets/byeonghwikim/abp_dataset json_feat_2.1.0
But, there is an error message in the part of loading resnet features (138 lines in seq2seq_im_mask.py file):
_pickle.UnpicklingError: invalid load key, 'v'
(I already tried to download dataset several times.)

That seems expected.
Can you try `data/json_feat_2.1.0` not just `json_feat_2.1.0`?
The code loads image features stored in `data/json_feat_2.1.0`

**Comment by hjson1022** [comment]
I think it is not a problem.
I tried to download both cases, but still there is same error message.

#1
cd data
git clone https://huggingface.co/datasets/byeonghwikim/abp_dataset json_feat_2.1.0

#2
git clone https://huggingface.co/datasets/byeonghwikim/abp_dataset data/json_feat_2.1.0

**Comment by bhkim94** [comment]
Closing this issue. Feel free to reopen this if you have any further questions.

**Comment by hjson1022** [comment]
I solved the problem. Thanks

solution:
sudo apt-get install git-lfs
git lfs install

**Comment by bhkim94** [comment]
Thank you for sharing your solution!
