### ISSUE TITLE
Does cl-alfred have a smaller dataset?

### ISSUE THREAD

**Issue by zhang-qihao** [snumprlab/cl-alfred#7]
The 1.6T dataset is too big, is there a smaller one that allows me to train the model quickly?

**Comment by bhkim94** [comment]
Hi @zhang-qihao,

Thank you for your interest in our work!
We are planning to release the dataset with no image augmentation, which should reduce the dataset size to 1/7 in theory.
We are also releasing the raw RGB images of the dataset soon, so you can use them to build a smaller version of the dataset.

Hope this helps!

**Comment by bhkim94** [comment]
Hi @zhang-qihao,

We uploaded raw RGB images (with corresponding depths and object masks), so you can use them to build a smaller version of the dataset (*e.g.*, using no augmentation, using only egocentric images, *etc.*).
Let me know if you have any further questions.
